service: quotes

provider:
  name: aws
  runtime: python3.6
  stage: beta
  region: us-east-2
  memorySize: 128
  profile: my
  endpointType: REGIONAL
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:ListBucket"
        - "s3:PutObject"
      Resource: "arn:aws:s3:::my-aws-two/test/*"


plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  wsgi:
    app: main.app
    packRequirements: false

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'